[package]
name = "patina-dst-fs-mem"
description = "Deterministic in-memory filesystem driver for Patina"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
patina-dst-abi.workspace = true
patina-dst-driver-api.workspace = true
