[package]
name = "patina-fs-crash"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
patina-abi.workspace = true
patina-driver-api.workspace = true
patina-fs-mem.workspace = true
patina-rng-seeded.workspace = true
