//! Embedded shim sources, toolchain agreement, builds, and object staging.

use crate::native_build::{
    GuestInstrumentation, PATINA_COV_C, PATINA_SANCOV_STUB_C, PATINA_YIELD_C, hash_file_contents,
    host_target_triple,
};
use crate::{CliError, hash_bytes, hash_os, hex, output, shim_cache};
use patina_dst_trace::lock_exclusive;
use sha2::{Digest, Sha256};
use std::ffi::{OsStr, OsString};
use std::fs::OpenOptions;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs, io};

// The native link recipe is packaged into `cargo patina` so `native-build` can
// reproduce it without the source tree: the POSIX shim C layer and its header
// are embedded, compiled below the user program, and linked against the
// `patina-dst-native-shim` staticlib. The C text is sourced from the shim crate
// itself (its `pub const`s) rather than an `include_str!` across the crate
// boundary, so there is a single copy of the C that cannot drift and both
// crates package cleanly for publish.
const PATINA_POSIX_C: &str = patina_dst_native_shim::POSIX_C_SOURCE;
/// The per-family slices the umbrella `#include`s, staged beside it.
const PATINA_POSIX_C_FAMILIES: &[(&str, &str)] = patina_dst_native_shim::POSIX_C_FAMILY_SOURCES;
const PATINA_NATIVE_H: &str = patina_dst_native_shim::NATIVE_HEADER;
/// The embedded native-shim source bundle, generated by `build.rs`: the shim's
/// whole workspace dependency closure (12 crates) plus the pinning `Cargo.lock`,
/// content-addressed by `EMBEDDED_SHIM_BUNDLE_SHA256`. Carrying the source (not a
/// prebuilt staticlib) lets an installed `cargo-patina` compile the shim with the
/// exact rustc that compiles the guest — the identity the toolchain check pins.
mod shim_bundle {
    include!(concat!(env!("OUT_DIR"), "/shim_sources.rs"));
}

const NATIVE_SHIM_STATICLIB: &str = "libpatina_dst_native_shim.a";
/// Subdirectory of the shim's own profile target dir where the content-addressed
/// POSIX/yield helper objects are staged, so their `-Clink-arg` paths stay stable
/// across builds and Cargo's crate fingerprints stay warm.
const NATIVE_SHIM_OBJECTS_DIR: &str = "patina-shim-objects";
/// Lock file in every Cargo target dir cargo-patina builds in; see
/// [`lock_target_dir`].
pub(super) const TARGET_DIR_LOCK: &str = ".patina-build.lock";

pub(super) fn link_arg(path: &Path) -> OsString {
    let mut arg = OsString::from("link-arg=");
    arg.push(path);
    arg
}

/// The per-user cache root that holds the unpacked shim source bundle and, by
/// default, its build: `$XDG_CACHE_HOME/patina` when set (any platform), else
/// `~/Library/Caches/patina` on macOS and `~/.cache/patina` elsewhere. No `HOME`
/// is a loud error, never a fallback into the working directory.
fn patina_cache_root() -> Result<PathBuf, CliError> {
    if let Some(xdg) = env::var_os("XDG_CACHE_HOME").filter(|value| !value.is_empty()) {
        let xdg = PathBuf::from(xdg);
        if !xdg.is_absolute() {
            return Err(CliError(format!(
                "XDG_CACHE_HOME must be an absolute path, got {}",
                xdg.display()
            )));
        }
        return Ok(xdg.join("patina"));
    }
    let home = env::var_os("HOME")
        .filter(|value| !value.is_empty())
        .ok_or_else(|| {
            CliError(
                "HOME is not set: cargo-patina places its shim source cache under it (or under \
                 XDG_CACHE_HOME when that is set)"
                    .into(),
            )
        })?;
    let home = PathBuf::from(home);
    Ok(if cfg!(target_os = "macos") {
        home.join("Library").join("Caches").join("patina")
    } else {
        home.join(".cache").join("patina")
    })
}

/// The unpacked shim source workspace, and the cache root it lives under.
pub(super) struct ShimSources {
    cache_root: PathBuf,
    /// `<cache_root>/shim-src/<bundle sha256>`: a self-contained Cargo workspace
    /// holding the shim's whole dependency closure, the pinning `Cargo.lock`, and
    /// no toolchain pin of its own.
    pub(super) dir: PathBuf,
    /// The content address of the embedded source bundle that produced `dir`.
    bundle_hash: &'static str,
    // Pins sources from before toolchain probing through the last guest link.
    _lease: shim_cache::Lease,
}

pub(super) struct BuiltNativeShim {
    pub(super) staticlib: PathBuf,
    // Guest builders must retain this, not just the path, until linking ends.
    pub(super) _lease: shim_cache::Lease,
}

/// Unpack the embedded shim source bundle into the per-user cache (a no-op when
/// this binary's bundle is already there) and return where it lives.
///
/// `cargo-patina` carries the shim's source, not a prebuilt staticlib: the shim
/// must be compiled by the exact rustc that compiles the guest, so the build
/// happens on the user's machine, from a directory this binary owns. That is
/// what lets `build`/`run`/`audit`/`replay` of a source or package succeed from
/// any working directory and from an installed binary alike — `cargo build -p
/// patina-dst-native-shim` runs in a private copy of the unpacked workspace, never in the
/// caller's CWD (where the shim crate would not resolve) and never in a source
/// checkout (which an installed binary does not have).
pub(super) fn prepare_shim_sources() -> Result<ShimSources, CliError> {
    let cache_root = patina_cache_root()?;
    let lease = shim_cache::acquire_initialized(
        &cache_root.join("shim-src"),
        shim_bundle::EMBEDDED_SHIM_BUNDLE_SHA256,
        shim_cache::KEEP_SOURCES,
        || unpack_embedded_shim_sources(&cache_root).map(|_| ()),
    )?;
    Ok(ShimSources {
        cache_root,
        dir: lease.dir.clone(),
        bundle_hash: shim_bundle::EMBEDDED_SHIM_BUNDLE_SHA256,
        _lease: lease,
    })
}

/// Write the bundle to `<cache_root>/shim-src/<sha256>` atomically: stage into
/// a temporary sibling and rename into place, with a completion marker written
/// last. The caller holds the source catalog lock. Incomplete/old directories
/// are retired before repair; directory existence alone is never a cache hit.
fn unpack_embedded_shim_sources(cache_root: &Path) -> Result<PathBuf, CliError> {
    let bundles = cache_root.join("shim-src");
    let bundle_dir = bundles.join(shim_bundle::EMBEDDED_SHIM_BUNDLE_SHA256);
    if shim_cache::complete(&bundle_dir, shim_bundle::EMBEDDED_SHIM_BUNDLE_SHA256)? {
        return Ok(bundle_dir);
    }
    if bundle_dir.exists() {
        shim_cache::retire(&bundle_dir)?;
    }
    let io = |what: String, error: io::Error| CliError(format!("{what}: {error}"));
    fs::create_dir_all(&bundles)
        .map_err(|error| io(format!("creating {}", bundles.display()), error))?;
    let stage = tempfile::Builder::new()
        .prefix(".staging-")
        .tempdir_in(&bundles)
        .map_err(|error| {
            io(
                format!("staging shim sources in {}", bundles.display()),
                error,
            )
        })?;
    let staging = stage.path();
    let write = |relative: &Path, bytes: &[u8]| -> Result<(), CliError> {
        let path = staging.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| io(format!("creating {}", parent.display()), error))?;
        }
        fs::write(&path, bytes).map_err(|error| io(format!("writing {}", path.display()), error))
    };
    let mut members = String::new();
    for (package, files) in shim_bundle::EMBEDDED_SHIM_SOURCES {
        members.push_str(&format!("    {package:?},\n"));
        for (relative, bytes) in *files {
            write(&Path::new(package).join(relative), bytes)?;
        }
    }
    // The unpacked closure is its own workspace: every member is addressed by
    // package name (its manifests were repointed to `../<package-name>` when the
    // bundle was packed), and the lock pins the third-party crates.
    write(
        Path::new("Cargo.toml"),
        format!(
            "# @generated by cargo-patina: the native shim's build workspace. Do not edit.\n\
             [workspace]\nmembers = [\n{members}]\nresolver = \"2\"\n"
        )
        .as_bytes(),
    )?;
    write(
        Path::new("Cargo.lock"),
        shim_bundle::EMBEDDED_SHIM_CARGO_LOCK,
    )?;
    write(
        Path::new(shim_cache::COMPLETE),
        shim_bundle::EMBEDDED_SHIM_BUNDLE_SHA256.as_bytes(),
    )?;
    fs::rename(staging, &bundle_dir).map_err(|error| {
        io(
            format!("publishing shim sources at {}", bundle_dir.display()),
            error,
        )
    })?;
    Ok(bundle_dir)
}

/// Build in reusable scratch state; publish and pin only immutable link inputs.
pub(super) fn build_native_shim(
    release: bool,
    rustc: &RustcInvocation,
    shim: &ShimSources,
    instrumentation: GuestInstrumentation,
) -> Result<BuiltNativeShim, CliError> {
    let explicit = env::var_os("CARGO_TARGET_DIR");
    build_native_shim_at(release, rustc, shim, explicit.as_deref(), instrumentation)
}

fn build_native_shim_at(
    release: bool,
    rustc: &RustcInvocation,
    shim: &ShimSources,
    explicit: Option<&OsStr>,
    instrumentation: GuestInstrumentation,
) -> Result<BuiltNativeShim, CliError> {
    let base = native_shim_cache_base(&shim.cache_root, explicit)?;
    shim_cache::prune_legacy(&base);
    let profile = if release { "release" } else { "debug" };
    let mut hasher = Sha256::new();
    // One Cargo target already separates debug/release. Keep two toolchains
    // warm, not merely two toolchain/profile combinations.
    hash_bytes(&mut hasher, rustc.identity.verbose.as_bytes());
    let work = shim_cache::acquire(
        &base.join("builds"),
        &hex(&hasher.finalize()),
        shim_cache::KEEP_BUILDS,
    )?;
    // Pin before waiting: the pruner must not unlink this lock's inode while a
    // second builder is queued. Only the Cargo build is serialized, not links.
    let _lock = lock_target_dir(&work.dir)?;
    let target_dir = work.dir.join("target");
    let source_dir = work.dir.join("source");
    let marker = work.dir.join("bundle");
    let previous = match fs::read_to_string(&marker) {
        Ok(value) => Some(value),
        Err(e) if e.kind() == io::ErrorKind::NotFound => None,
        Err(e) => return Err(CliError(format!("reading {}: {e}", marker.display()))),
    };
    let needs_switch = previous.as_deref() != Some(shim.bundle_hash)
        || !shim_cache::complete(&source_dir, shim.bundle_hash)?;
    // Size is a high-water mark, not a mid-build quota. A single build may be
    // larger; its next use resets scratch state without touching pinned links.
    shim_cache::trim_build_target(&work.dir);
    if needs_switch {
        // Invalidate BEFORE changing sources. A crash halfway through a switch
        // must not let the previous bundle mistake this workspace for its own.
        if previous.is_some() {
            fs::remove_file(&marker)
                .map_err(|e| CliError(format!("invalidating shim bundle marker: {e}")))?;
        }
        if source_dir.exists() {
            fs::remove_dir_all(&source_dir)
                .map_err(|e| CliError(format!("resetting shim build sources: {e}")))?;
        }
        shim_cache::copy_sources(&shim.dir, &source_dir)?;
    }
    let command = || {
        let mut command = Command::new(&rustc.cargo_command);
        command
            .current_dir(&source_dir)
            .env("CARGO_TARGET_DIR", &target_dir)
            // Cargo >=1.91 can redirect intermediate state independently. Keep
            // it in our bounded scratch too; older Cargo ignores this variable.
            .env("CARGO_BUILD_BUILD_DIR", &target_dir)
            // Private scratch state needs neither incremental history nor full
            // type debug info. Level 1 retains backtraces and source locations.
            .env("CARGO_INCREMENTAL", "0")
            .env("CARGO_PROFILE_DEV_DEBUG", "1");
        apply_rustc_env(&mut command, rustc);
        command
    };
    if needs_switch {
        // Never trust Cargo's freshness of an older restored bundle. Clean only
        // local closure packages: registry dependencies stay reusable. This also
        // bounds obsolete local artifacts as source versions change.
        let mut clean = command();
        shim_cache::inherit(&mut clean, &work)?;
        clean.arg("clean");
        for (package, _) in shim_bundle::EMBEDDED_SHIM_SOURCES {
            clean.arg("-p").arg(package);
        }
        let status = clean
            .status()
            .map_err(|e| CliError(format!("cleaning shim packages: {e}")))?;
        if !status.success() {
            return Err(CliError("cleaning shim packages failed".into()));
        }
        // Write only after successful invalidation. A crash or failed build
        // leaves Cargo's own incomplete-build fingerprint to force a retry.
        fs::write(source_dir.join(shim_cache::COMPLETE), shim.bundle_hash)
            .map_err(|e| CliError(format!("completing shim build sources: {e}")))?;
        fs::write(&marker, shim.bundle_hash)
            .map_err(|e| CliError(format!("writing shim bundle marker: {e}")))?;
    }
    let mut build = command();
    shim_cache::inherit(&mut build, &work)?;
    build.args(["rustc", "--lib", "--locked", "-p", "patina-dst-native-shim"]);
    if release {
        build.arg("--release");
    }
    build
        .arg("--")
        .args(patina_dst_native_shim::POSIX_RUST_FLAGS);
    let status = build
        .status()
        .map_err(|e| CliError(format!("building shim: {e}")))?;
    if !status.success() {
        return Err(CliError(
            "building the patina-dst-native-shim staticlib failed".into(),
        ));
    }
    let staticlib = target_dir.join(profile).join(NATIVE_SHIM_STATICLIB);
    // C compiler and instrumentation variants get independently evictable
    // entries, rather than accumulating objects inside one eternally hot entry.
    let cc = env::var_os("CC").unwrap_or_else(|| "cc".into());
    let c_identity = shim_object_hash(&cc, &PATINA_POSIX_OBJECT, &host_target_triple(rustc)?, &[])?;
    let recipe = format!("{profile}:{c_identity}:{instrumentation:?}");
    publish_native_shim(
        &staticlib,
        &base,
        shim.bundle_hash,
        &rustc.identity,
        &recipe,
    )
}

/// The archive digest also distinguishes ambient Cargo configuration changes.
/// Publication is an atomic file rename; helper objects are likewise published
/// atomically below the pinned entry and are never read from Cargo scratch.
fn publish_native_shim(
    staticlib: &Path,
    base: &Path,
    bundle: &str,
    toolchain: &RustcIdentity,
    profile: &str,
) -> Result<BuiltNativeShim, CliError> {
    let mut hasher = Sha256::new();
    hash_file_contents(&mut hasher, staticlib)?;
    hash_bytes(&mut hasher, bundle.as_bytes());
    hash_bytes(&mut hasher, toolchain.verbose.as_bytes());
    hash_bytes(&mut hasher, profile.as_bytes());
    let lease = shim_cache::acquire(
        &base.join("artifacts"),
        &hex(&hasher.finalize()),
        shim_cache::KEEP_ARTIFACTS,
    )?;
    let _lock = lock_target_dir(&lease.dir)?;
    let published = lease.dir.join(NATIVE_SHIM_STATICLIB);
    let partial = lease.dir.join("archive.partial");
    shim_cache::clear_partial(&partial)?;
    if !published.exists() {
        shim_cache::copy(staticlib, &partial)?;
        fs::rename(&partial, &published)
            .map_err(|e| CliError(format!("publishing shim archive: {e}")))?;
    }
    Ok(BuiltNativeShim {
        staticlib: published,
        _lease: lease,
    })
}

/// Hold `target_dir`'s build lock until the returned file is dropped; the
/// kernel releases it if the process dies.
///
/// Cargo rewrites every output in its target dir on every invocation, fresh or
/// not, wherever it copies rather than hard-links (always on macOS; on Linux
/// when the build dir is on another filesystem), and its own lock ends when
/// Cargo exits. A caller that reads an output back after Cargo returns — the
/// shim archive it publishes, the guest executable it copies out — therefore
/// holds this from before its Cargo invocation until that read is done, or a
/// concurrent build's Cargo can rewrite the file mid-read. OpenOptions creates
/// CLOEXEC descriptors on Unix; keep that flag set for build and catalog locks
/// so a compiler wrapper's daemon cannot retain an exclusive lock after exec.
pub(super) fn lock_target_dir(target_dir: &Path) -> Result<fs::File, CliError> {
    fs::create_dir_all(target_dir).map_err(|error| {
        CliError(format!(
            "failed to create target dir {}: {error}",
            target_dir.display()
        ))
    })?;
    let path = target_dir.join(TARGET_DIR_LOCK);
    let file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(false)
        .open(&path)
        .map_err(|error| CliError(format!("failed to open {}: {error}", path.display())))?;
    lock_exclusive(&file, true)
        .map_err(|error| CliError(format!("failed to lock {}: {error}", path.display())))?;
    Ok(file)
}

/// Explicit CARGO_TARGET_DIR remains the base, never a replacement for Patina's
/// namespace. Anchor relative paths before Cargo changes into the source cache.
fn native_shim_cache_base(
    cache_root: &Path,
    explicit: Option<&OsStr>,
) -> Result<PathBuf, CliError> {
    let base = explicit
        .map(PathBuf::from)
        .unwrap_or_else(|| cache_root.join("shim-target"));
    std::path::absolute(base.join("patina-native-shim"))
        .map_err(|e| CliError(format!("resolving shim cache base: {e}")))
}

/// A resolved rustc, as `rustc -vV` reports it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct RustcIdentity {
    /// The `rustc -vV` banner line, e.g. `rustc 1.98.1 (48a229cea 2026-09-01)`.
    banner: String,
    /// The full `-vV` block: release, commit hash, host triple, LLVM version.
    pub(super) verbose: String,
}

#[derive(Debug, Clone)]
pub(super) struct RustcInvocation {
    pub(super) command: OsString,
    pub(super) cargo_command: OsString,
    pub(super) identity: RustcIdentity,
}

fn rustc_invocation_from_env(from: &Path) -> (OsString, Option<OsString>) {
    (
        anchored_program(env::var_os("RUSTC"), from, "rustc"),
        env::var_os("CARGO").map(|cargo| anchored_program(Some(cargo), from, "cargo")),
    )
}

pub(super) fn apply_rustc_env(command: &mut Command, rustc: &RustcInvocation) {
    command.env("RUSTC", &rustc.command);
}

/// Resolve the rustc that compiles code in `directory`.
///
/// The working directory is the input that matters. Under rustup, the `rustc` on
/// `PATH` is a proxy that picks its toolchain from the `rust-toolchain.toml`
/// found by walking up from wherever it runs, and Cargo inherits that: even a
/// toolchain's own `cargo` binary invokes the `PATH` proxy for `rustc`, so the
/// directory a build runs in — not the `cargo` that drives it — can decide which
/// compiler compiles the crate. Other directory-scoped selectors behave likewise;
/// a concrete compiler should report the same identity from every directory.
fn rustc_identity(rustc: &OsStr, directory: &Path) -> Result<RustcIdentity, CliError> {
    let output = Command::new(rustc)
        .arg("-vV")
        .current_dir(directory)
        .output()
        .map_err(|error| {
            CliError(format!(
                "failed to query the rustc identity in {}: {error}",
                directory.display()
            ))
        })?;
    if !output.status.success() {
        return Err(CliError(format!(
            "rustc -vV failed in {}: {}",
            directory.display(),
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let verbose = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    let banner = verbose.lines().next().unwrap_or_default().to_owned();
    if banner.is_empty() {
        return Err(CliError(format!(
            "rustc -vV reported no version in {}",
            directory.display()
        )));
    }
    Ok(RustcIdentity { banner, verbose })
}

/// The compiler to probe with, honoring `RUSTC` exactly as the builds do so an
/// explicitly pinned compiler probes as the single identity it is.
///
/// The two probes run in two different directories, so the value must name the
/// same program from both. A bare name is left alone (the OS resolves it against
/// `PATH`, which does not depend on the working directory); a relative path with
/// a directory component would resolve against each probe's own directory, so it
/// is anchored to `from` first.
fn anchored_program(program: Option<OsString>, from: &Path, fallback: &str) -> OsString {
    let Some(program) = program else {
        return OsString::from(fallback);
    };
    let path = Path::new(&program);
    let has_directory = path
        .parent()
        .is_some_and(|parent| !parent.as_os_str().is_empty());
    if path.is_relative() && has_directory {
        from.join(path).into_os_string()
    } else {
        program
    }
}

/// Materialize the guest compiler once; never resolve an ambient compiler in
/// the shared shim cache. Two stdlibs cause a duplicate rust_eh_personality on
/// Linux and can silently link on macOS.
///
/// A -vV banner is an identity, NOT a selector: it cannot encode a rustup name,
/// `stable`, a mise version, or a Nix path. RUSTUP_TOOLCHAIN / +toolchain are
/// rustup-specific, and writing rust-toolchain.toml into the content-addressed
/// bundle would mutate shared input and race concurrent builds. Instead verify
/// the sysroot's absolute compiler in BOTH directories and use it everywhere.
pub(super) fn check_native_toolchain_agreement(
    shim_dir: &Path,
) -> Result<RustcInvocation, CliError> {
    let guest_dir = env::current_dir()
        .map_err(|error| CliError(format!("failed to read the working directory: {error}")))?;
    let (selected, explicit_cargo) = rustc_invocation_from_env(&guest_dir);
    let refusal = |reason: String| {
        CliError(format!(
            "refusing to build: cannot prove one rustc toolchain for the guest in {} and the shim in {}: {reason}\n\
         invoke cargo-patina with absolute, matching RUSTC and CARGO binaries from one toolchain; \
         the compiler must expose a sysroot with bin/rustc and bin/cargo. No ambient fallback is used.",
            guest_dir.display(),
            shim_dir.display()
        ))
    };
    let guest = rustc_identity(&selected, &guest_dir).map_err(|e| refusal(e.0))?;
    let output = Command::new(&selected)
        .args(["--print", "sysroot"])
        .current_dir(&guest_dir)
        .output()
        .map_err(|e| {
            refusal(format!(
                "guest toolchain {}: failed to query sysroot: {e}",
                guest.banner
            ))
        })?;
    if !output.status.success() {
        return Err(refusal(format!(
            "guest toolchain {}: rustc --print sysroot failed: {}",
            guest.banner,
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let sysroot = std::str::from_utf8(&output.stdout)
        .map_err(|e| refusal(format!("invalid sysroot: {e}")))?
        .trim();
    let sysroot = Path::new(sysroot);
    if !sysroot.is_absolute() {
        return Err(refusal(format!(
            "guest toolchain {}: sysroot is not an absolute path: {sysroot:?}",
            guest.banner
        )));
    }
    let command = sysroot.join("bin/rustc").into_os_string();
    let cargo = sysroot.join("bin/cargo");
    if !Path::new(&command).is_file() || !cargo.is_file() {
        return Err(refusal(format!(
            "guest toolchain {}: missing bin/rustc or bin/cargo in {}",
            guest.banner,
            sysroot.display()
        )));
    }
    for directory in [&guest_dir, shim_dir] {
        let verified = rustc_identity(&command, directory).map_err(|e| refusal(e.0))?;
        if verified != guest {
            return Err(CliError(toolchain_mismatch_message(
                &verified, directory, &guest, &guest_dir,
            )));
        }
    }
    Ok(RustcInvocation {
        command,
        cargo_command: explicit_cargo.unwrap_or_else(|| cargo.into_os_string()),
        identity: guest,
    })
}

/// Name the selected and materialized identities and the verification directory,
/// with a proxy-agnostic remedy. Never turn an identity banner into a selector.
fn toolchain_mismatch_message(
    shim: &RustcIdentity,
    shim_dir: &Path,
    guest: &RustcIdentity,
    guest_dir: &Path,
) -> String {
    let mut message = String::from(
        "refusing to build: the Patina shim staticlib and the guest program would be compiled by \
two different rustc toolchains, so two Rust standard libraries would meet at the guest link \
(`duplicate symbol: rust_eh_personality` on Linux; on macOS the link silently succeeds and the \
guest carries both).\n",
    );
    message.push_str(&format!(
        "  shim toolchain:  {} (resolved in {})\n  guest toolchain: {} (resolved in {})\n",
        shim.banner,
        shim_dir.display(),
        guest.banner,
        guest_dir.display()
    ));
    if shim.banner == guest.banner {
        // Same release, different compiler: show the full identities so the
        // difference (commit hash, host triple, LLVM version) is visible.
        message.push_str(&format!(
            "the two report the same version but are not the same compiler:\n  shim:\n{}\n  \
guest:\n{}\n",
            indent_lines(&shim.verbose, "    "),
            indent_lines(&guest.verbose, "    ")
        ));
    }
    message.push_str(
        "the absolute compiler in the guest's sysroot could not be verified against the \
selected guest identity. No ambient fallback is used. Invoke cargo-patina with absolute, matching \
RUSTC and CARGO binaries from one toolchain.",
    );
    message
}

/// Prefix every line of `text` with `indent`.
fn indent_lines(text: &str, indent: &str) -> String {
    text.lines()
        .map(|line| format!("{indent}{line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// A shim helper object compiled below the guest and linked into every native
/// build. Both variants are content-addressed by [`stage_shim_object`]: the POSIX
/// layer always, the `--yield-points` hook only under that flag.
pub(super) struct ShimObject {
    /// Final object file name, e.g. `patina_posix.o`.
    object_name: &'static str,
    /// C translation-unit file name written into the compile sandbox.
    source_name: &'static str,
    /// Embedded C source compiled into the object.
    source: &'static str,
    /// Header staged beside the source and reached through `-I`, if any.
    header: Option<(&'static str, &'static str)>,
    /// Further sources the translation unit `#include`s by relative path,
    /// staged beside it (subdirectories created) and folded into the hash.
    companion_sources: &'static [(&'static str, &'static str)],
    /// `cc` flags, excluding `-c`/`-I`/the input path/`-o` (added by the stager).
    cc_flags: &'static [&'static str],
    /// What the object is, for staging/compilation diagnostics.
    what: &'static str,
}

/// The embedded POSIX shim C layer, compiled below the user program with the
/// flags the deterministic linked target requires.
pub(super) const PATINA_POSIX_OBJECT: ShimObject = ShimObject {
    object_name: "patina_posix.o",
    source_name: "patina_posix.c",
    source: PATINA_POSIX_C,
    header: Some(("patina_native.h", PATINA_NATIVE_H)),
    companion_sources: PATINA_POSIX_C_FAMILIES,
    cc_flags: patina_dst_native_shim::POSIX_C_FLAGS,
    what: "the Patina POSIX shim layer",
};

/// The `--yield-points` hook object. Compiled without the SanitizerCoverage flags
/// themselves, so the hook (and thus `patina_yield_point` it calls) is never
/// itself instrumented and cannot recurse.
const PATINA_YIELD_OBJECT: ShimObject = ShimObject {
    object_name: "patina_yield.o",
    source_name: "patina_yield.c",
    source: PATINA_YIELD_C,
    header: None,
    companion_sources: &[],
    cc_flags: &[
        "-std=c11",
        "-fno-stack-protector",
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
    what: "the Patina yield-point hook",
};

/// The `--coverage-points` hook object: the same SanitizerCoverage entry points
/// as [`PATINA_YIELD_OBJECT`] with the scheduler call made optional and sampled.
/// Its sampling stride arrives as a `-DPATINA_YIELD_STRIDE=N` define, which
/// [`shim_object_hash`] folds in, so each stride gets its own content-addressed
/// object and two strides can never share one. Compiled without the
/// SanitizerCoverage flags themselves, so the hook is never itself instrumented.
const PATINA_COV_OBJECT: ShimObject = ShimObject {
    object_name: "patina_cov.o",
    source_name: "patina_cov.c",
    source: PATINA_COV_C,
    header: None,
    companion_sources: &[],
    cc_flags: &[
        "-std=c11",
        "-fno-stack-protector",
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
    what: "the Patina coverage-point hook",
};

/// The weak SanitizerCoverage stubs. Unlike every other shim object this one is
/// injected whole-graph rather than scoped to the guest's final link, because the
/// instrumentation it answers for is whole-graph too — so it must be
/// position-independent: the artifacts that need it are shared libraries, and a
/// non-PIC object referencing anything by absolute address is refused outright by
/// GNU `ld`/`lld` inside a shared-object link. macOS `cc` compiles PIC by
/// default, so the flag is a no-op there.
pub(super) const PATINA_SANCOV_STUB_OBJECT: ShimObject = ShimObject {
    object_name: "patina_sancov_stub.o",
    source_name: "patina_sancov_stub.c",
    source: PATINA_SANCOV_STUB_C,
    header: None,
    companion_sources: &[],
    cc_flags: &[
        "-std=c11",
        "-fno-stack-protector",
        "-fPIC",
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
    what: "the Patina SanitizerCoverage stubs",
};

/// Hash the inputs that determine a shim object's bytes: the compiler identity
/// and its `--version` banner, the target triple, the object name, the exact cc
/// flags, and the embedded C header/source. The staged path changes only when one
/// of these does, so a rebuild of the same Patina against the same toolchain
/// reuses the object and the `-Clink-arg` path stays stable.
fn shim_object_hash(
    cc: &OsStr,
    object: &ShimObject,
    target: &str,
    defines: &[String],
) -> Result<String, CliError> {
    let version = Command::new(cc)
        .arg("--version")
        .output()
        .map_err(|error| CliError(format!("failed to query C compiler {cc:?}: {error}")))?;
    if !version.status.success() {
        return Err(CliError(format!("C compiler {cc:?} --version failed")));
    }
    let mut hasher = Sha256::new();
    hash_os(&mut hasher, cc);
    hash_bytes(&mut hasher, &version.stdout);
    hash_bytes(&mut hasher, target.as_bytes());
    hash_bytes(&mut hasher, object.object_name.as_bytes());
    for flag in object.cc_flags {
        hash_bytes(&mut hasher, flag.as_bytes());
    }
    for define in defines {
        hash_bytes(&mut hasher, define.as_bytes());
    }
    if let Some((header_name, header_source)) = object.header {
        hash_bytes(&mut hasher, header_name.as_bytes());
        hash_bytes(&mut hasher, header_source.as_bytes());
    }
    for (relative, source) in object.companion_sources {
        hash_bytes(&mut hasher, relative.as_bytes());
        hash_bytes(&mut hasher, source.as_bytes());
    }
    hash_bytes(&mut hasher, object.source.as_bytes());
    Ok(hex(&hasher.finalize()))
}

/// Stage the SanitizerCoverage hook object this build's instrumentation calls
/// for, and announce it on stdout (stderr under `--format json`, so the JSON
/// document stays parseable).
///
/// `None` for a plain build: its link recipe then contains no SanitizerCoverage
/// flags and no hook object, so a plain native build is byte-for-byte the build
/// it was before any instrumentation existed.
pub(super) fn stage_instrumentation_object(
    shim: &BuiltNativeShim,
    instrumentation: GuestInstrumentation,
    host_target: &str,
) -> Result<Option<PathBuf>, CliError> {
    let (object, defines) = match instrumentation {
        GuestInstrumentation::None => return Ok(None),
        GuestInstrumentation::YieldPoints => (&PATINA_YIELD_OBJECT, Vec::new()),
        GuestInstrumentation::CoveragePoints { stride } => (
            &PATINA_COV_OBJECT,
            // Baked in at compile time, not read from the environment: the
            // sampling rate is part of the schedule policy, so it must be a
            // property of the BINARY (which the run side reads back out of the
            // marker) rather than something a later run could change under a
            // recorded trace.
            vec![format!("-DPATINA_YIELD_STRIDE={stride}")],
        ),
    };
    // Surface the instrumentation prominently: this binary is not a plain build —
    // it carries LLVM SanitizerCoverage, and `native-run` schedules it under a
    // distinct policy recorded in its compatibility fingerprint.
    let scheduler_hook = if instrumentation.preempts_inside_atomics() {
        "patina_yield_point"
    } else {
        "none"
    };
    let note = format!(
        "PATINA_NATIVE_BUILD_YIELD_POINTS instrumentation=llvm-sancov-trace-pc-guard \
mode={} scheduler-hook={scheduler_hook} fingerprint-suffix={} -- {}",
        instrumentation.mode_tag(),
        instrumentation.fingerprint_suffix(),
        instrumentation.describe()
    );
    if output::options().is_json() {
        eprintln!("{note}");
    } else {
        println!("{note}");
    }
    stage_shim_object(shim, object, host_target, &defines).map(Some)
}

/// Compile `object` to a stable, content-addressed path under `base` and return
/// it, reusing an already-staged object without recompiling. Staging is
/// race-safe: under its build lock the object is compiled in a private sandbox
/// to a fixed partial file, then atomically renamed into place. A retry clears
/// any interrupted partial. Production callers keep the artifact entry leased
/// until the guest link completes; eviction reclaims its helper objects together
/// with the archive.
pub(super) fn stage_shim_object(
    shim: &BuiltNativeShim,
    object: &ShimObject,
    target: &str,
    defines: &[String],
) -> Result<PathBuf, CliError> {
    let cc = env::var_os("CC").unwrap_or_else(|| OsString::from("cc"));
    let hash = shim_object_hash(&cc, object, target, defines)?;
    let dir = shim._lease.dir.join(NATIVE_SHIM_OBJECTS_DIR).join(hash);
    let _lock = lock_target_dir(&dir)?;
    let staged = dir.join(object.object_name);
    if staged.exists() {
        return Ok(staged);
    }
    fs::create_dir_all(&dir).map_err(|error| {
        CliError(format!(
            "failed to create the shim object cache {}: {error}",
            dir.display()
        ))
    })?;
    let sandbox = tempfile::tempdir().map_err(|error| {
        CliError(format!(
            "failed to create the shim compile sandbox: {error}"
        ))
    })?;
    let mut command = Command::new(&cc);
    command.args(object.cc_flags);
    command.args(defines);
    if let Some((header_name, header_source)) = object.header {
        fs::write(sandbox.path().join(header_name), header_source)
            .map_err(|error| CliError(format!("failed to stage {}: {error}", object.what)))?;
        command.arg("-I").arg(sandbox.path());
    }
    for (relative, source) in object.companion_sources {
        let path = sandbox.path().join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| CliError(format!("failed to stage {}: {error}", object.what)))?;
        }
        fs::write(&path, source)
            .map_err(|error| CliError(format!("failed to stage {}: {error}", object.what)))?;
    }
    let source_path = sandbox.path().join(object.source_name);
    fs::write(&source_path, object.source)
        .map_err(|error| CliError(format!("failed to stage {}: {error}", object.what)))?;
    let temp_object = dir.join("object.partial");
    shim_cache::clear_partial(&temp_object)?;
    shim_cache::inherit(&mut command, &shim._lease)?;
    command
        .arg("-c")
        .arg(&source_path)
        .arg("-o")
        .arg(&temp_object);
    let cc_status = command
        .status()
        .map_err(|error| CliError(format!("failed to run C compiler {cc:?}: {error}")))?;
    if !cc_status.success() {
        return Err(CliError(format!("compiling {} failed", object.what)));
    }
    fs::rename(&temp_object, &staged).map_err(|error| {
        CliError(format!(
            "failed to stage {} at {}: {error}",
            object.what,
            staged.display()
        ))
    })?;
    Ok(staged)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::native_build::GuestInstrumentation;
    use std::ffi::{OsStr, OsString};
    use std::fs::OpenOptions;
    use std::path::{Path, PathBuf};
    use std::process::Command;
    use std::{env, fs};

    use crate::shim_cache;

    #[test]
    fn a_relative_rustc_probes_as_one_program_from_both_directories() {
        let from = Path::new("/work/guest");
        // A bare name is PATH-resolved, which does not vary by directory.
        assert_eq!(
            anchored_program(None, from, "rustc"),
            OsString::from("rustc")
        );
        assert_eq!(
            anchored_program(Some("rustc".into()), from, "rustc"),
            OsString::from("rustc")
        );
        // An absolute path already names one program.
        assert_eq!(
            anchored_program(Some("/opt/rust/bin/rustc".into()), from, "rustc"),
            OsString::from("/opt/rust/bin/rustc")
        );
        // A relative path with a directory component would otherwise resolve
        // against each probe's own working directory — two different programs,
        // reported as a toolchain split that does not exist.
        assert_eq!(
            anchored_program(Some("./tools/rustc".into()), from, "rustc"),
            OsString::from("/work/guest/./tools/rustc")
        );
        assert_eq!(
            anchored_program(Some("tools/rustc".into()), from, "rustc"),
            OsString::from("/work/guest/tools/rustc")
        );
    }

    #[test]
    fn shim_caches_are_separated_by_source_bundle_and_complete_toolchain_identity() {
        let cache = tempfile::tempdir().unwrap();
        let workspace = cache.path();
        let archive = workspace.join("cargo.a");
        fs::write(&archive, b"stable archive").unwrap();
        let stable = RustcIdentity {
            banner: "rustc 1.98.0 (stable)".into(),
            verbose: "rustc 1.98.0 (stable)\ncommit-hash: stable".into(),
        };
        let other = RustcIdentity {
            banner: "rustc 1.98.1 (other)".into(),
            verbose: "rustc 1.98.1 (other)\ncommit-hash: other".into(),
        };
        let base = native_shim_cache_base(workspace, None).unwrap();
        let stable_artifact =
            publish_native_shim(&archive, &base, "bundle-a", &stable, "debug").unwrap();
        fs::write(&archive, b"other archive").unwrap();
        let other_artifact =
            publish_native_shim(&archive, &base, "bundle-a", &other, "debug").unwrap();
        let changed = publish_native_shim(&archive, &base, "bundle-b", &stable, "debug").unwrap();
        assert_ne!(stable_artifact.staticlib, other_artifact.staticlib);
        assert_ne!(stable_artifact.staticlib, changed.staticlib);
        let same_bytes_other_bundle =
            publish_native_shim(&archive, &base, "bundle-a", &stable, "debug").unwrap();
        assert_ne!(same_bytes_other_bundle.staticlib, changed.staticlib);
        assert_eq!(
            fs::read(&stable_artifact.staticlib).unwrap(),
            b"stable archive"
        );
        assert_eq!(
            fs::read(&other_artifact.staticlib).unwrap(),
            b"other archive"
        );
        // Equal banners and bytes still cannot alias different complete identities.
        let mut rebuilt_toolchain = stable.clone();
        rebuilt_toolchain
            .verbose
            .push_str("\nLLVM version: different");
        let rebuilt =
            publish_native_shim(&archive, &base, "bundle-b", &rebuilt_toolchain, "debug").unwrap();
        assert_ne!(rebuilt.staticlib, changed.staticlib);
        let release = publish_native_shim(&archive, &base, "bundle-b", &stable, "release").unwrap();
        assert_ne!(release.staticlib, changed.staticlib);

        assert_eq!(
            native_shim_cache_base(workspace, Some(OsStr::new("/custom-target"))).unwrap(),
            PathBuf::from("/custom-target/patina-native-shim")
        );
        assert_eq!(
            native_shim_cache_base(workspace, Some(OsStr::new("relative"))).unwrap(),
            env::current_dir()
                .unwrap()
                .join("relative/patina-native-shim")
        );
    }

    #[test]
    fn incomplete_shim_source_bundle_is_repaired() {
        let cache = tempfile::tempdir().unwrap();
        let bundles = cache.path().join("shim-src");
        let key = shim_bundle::EMBEDDED_SHIM_BUNDLE_SHA256;
        let partial = bundles.join(key);
        fs::create_dir_all(&partial).unwrap();
        fs::write(partial.join("Cargo.toml"), b"interrupted old extraction").unwrap();
        let lease = shim_cache::acquire_initialized(&bundles, key, 1, || {
            unpack_embedded_shim_sources(cache.path()).map(|_| ())
        })
        .unwrap();
        assert!(shim_cache::complete(&lease.dir, key).unwrap());
        for (package, files) in shim_bundle::EMBEDDED_SHIM_SOURCES {
            for (path, bytes) in *files {
                assert_eq!(
                    fs::read(lease.dir.join(package).join(path)).unwrap(),
                    *bytes
                );
            }
        }
    }

    /// Build real archives with deliberately different link-time answers. This
    /// is the class-level detector for restored-bundle Cargo freshness, mutable
    /// output handoff, and cross-bundle concurrent builds (not just key strings).
    #[test]
    #[cfg(unix)]
    fn concurrent_shim_bundles_link_their_own_archives_after_a_bundle_restore() {
        if shim_cache::isolated_test(
            "tests::concurrent_shim_bundles_link_their_own_archives_after_a_bundle_restore",
        ) {
            return;
        }
        let cache = tempfile::tempdir().unwrap();
        let make_bundle = |key: &'static str, answer: u32| {
            let lease = shim_cache::acquire(&cache.path().join("shim-src"), key, 4).unwrap();
            // Even an ambient/configured Cargo intermediate directory must not
            // escape the leased, size-bounded scratch target.
            fs::create_dir_all(lease.dir.join(".cargo")).unwrap();
            fs::write(
                lease.dir.join(".cargo/config.toml"),
                format!(
                    "[build]\nbuild-dir = {:?}\n",
                    cache.path().join("escaped-build-dir")
                ),
            )
            .unwrap();
            let mut members = Vec::new();
            let mut lock = String::from("version = 3\n");
            for (package, _) in shim_bundle::EMBEDDED_SHIM_SOURCES {
                members.push(format!("{package:?}"));
                let dir = lease.dir.join(package);
                fs::create_dir_all(dir.join("src")).unwrap();
                let is_shim = *package == "patina-dst-native-shim";
                fs::write(dir.join("Cargo.toml"), format!(
                    "[package]\nname = {package:?}\nversion = \"0.0.0\"\nedition = \"2021\"\n{}",
                    if is_shim { "[lib]\ncrate-type = [\"staticlib\"]\n" } else { "" }
                )).unwrap();
                fs::write(dir.join("src/lib.rs"), if is_shim {
                    format!("#[no_mangle] pub extern \"C\" fn shim_cache_sentinel() -> u32 {{ {answer} }}\n")
                } else { String::new() }).unwrap();
                lock.push_str(&format!(
                    "\n[[package]]\nname = {package:?}\nversion = \"0.0.0\"\n"
                ));
            }
            fs::write(
                lease.dir.join("Cargo.toml"),
                format!(
                    "[workspace]\nresolver = \"2\"\nmembers = [{}]\n",
                    members.join(",")
                ),
            )
            .unwrap();
            fs::write(lease.dir.join("Cargo.lock"), lock).unwrap();
            ShimSources {
                cache_root: cache.path().into(),
                dir: lease.dir.clone(),
                bundle_hash: key,
                _lease: lease,
            }
        };
        let a = make_bundle("a", 17);
        let b = make_bundle("b", 29);
        let mut rustc = check_native_toolchain_agreement(&a.dir).unwrap();
        let quote = |path: &OsStr| format!("'{}'", path.to_str().unwrap().replace('\'', "'\\''"));
        // Reproduce clonefile-preserved timestamps on every platform. Without
        // clean -p, Cargo sees the old dep-info as fresh despite different bytes.
        let backdate = cache.path().join("cargo-backdate");
        fs::write(&backdate, format!(
            "#!/bin/sh\nset -eu\nfind . -type f -exec touch -t 200001010000 {{}} +\nexec {} \"$@\"\n",
            quote(&rustc.cargo_command)
        )).unwrap();
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&backdate, fs::Permissions::from_mode(0o755)).unwrap();
        rustc.cargo_command = backdate.as_os_str().into();
        let link = |built: &BuiltNativeShim, expected: u32| {
            let dir = tempfile::tempdir().unwrap();
            let source = dir.path().join("guest.c");
            let guest = dir.path().join("guest");
            fs::write(&source, format!("extern unsigned shim_cache_sentinel(void); int main(void) {{ return shim_cache_sentinel() != {expected}; }}")).unwrap();
            let mut cc = Command::new("cc");
            cc.arg(source).arg(&built.staticlib).arg("-o").arg(&guest);
            if cfg!(target_os = "linux") {
                cc.args(["-ldl", "-lpthread", "-lm"]);
            }
            assert!(cc.status().unwrap().success());
            assert!(Command::new(guest).status().unwrap().success());
        };
        // Both archive handles survive while another bundle overwrites Cargo's
        // same-named output. Rendezvous AFTER build, BEFORE either guest links.
        let barrier = std::sync::Barrier::new(2);
        std::thread::scope(|scope| {
            let handles: Vec<_> = [(&a, 17), (&b, 29)]
                .into_iter()
                .map(|(bundle, expected)| {
                    let rustc = &rustc;
                    let barrier = &barrier;
                    scope.spawn(move || {
                        barrier.wait();
                        (
                            build_native_shim_at(
                                false,
                                rustc,
                                bundle,
                                None,
                                GuestInstrumentation::None,
                            )
                            .unwrap(),
                            expected,
                        )
                    })
                })
                .collect();
            let built: Vec<_> = handles.into_iter().map(|h| h.join().unwrap()).collect();
            for (artifact, expected) in built {
                link(&artifact, expected);
            }
        });
        // Force A -> B -> A even if the concurrent scheduling chose B -> A.
        for (bundle, expected) in [(&a, 17), (&b, 29), (&a, 17)] {
            let built =
                build_native_shim_at(false, &rustc, bundle, None, GuestInstrumentation::None)
                    .unwrap();
            link(&built, expected);
        }
        assert!(!cache.path().join("escaped-build-dir").exists());

        // A compiler-wrapper server can outlive the command that started it.
        // It may pin shared state, but the next real build must acquire the
        // exclusive build lock without waiting for that server to exit.
        let fifo = cache.path().join("daemon-control");
        assert!(
            Command::new("mkfifo")
                .arg(&fifo)
                .status()
                .unwrap()
                .success()
        );
        struct ResumeDaemon(fs::File);
        impl Drop for ResumeDaemon {
            fn drop(&mut self) {
                use std::io::Write;
                let _ = self.0.write_all(b"finish\n");
            }
        }
        let resume = ResumeDaemon(
            OpenOptions::new()
                .read(true)
                .write(true)
                .open(&fifo)
                .unwrap(),
        );
        let ready = cache.path().join("daemon-ready");
        let claim = cache.path().join("daemon-started");
        let wrapper = cache.path().join("cargo-daemon-wrapper");
        fs::write(&wrapper, format!(
            "#!/bin/sh\nset -eu\nif [ \"$1\" = build ] && mkdir {} 2>/dev/null; then\n  (exec 3< {}; : > {}; read reply <&3) </dev/null >/dev/null 2>&1 &\nfi\nexec {} \"$@\"\n",
            quote(claim.as_os_str()), quote(fifo.as_os_str()), quote(ready.as_os_str()), quote(backdate.as_os_str())
        )).unwrap();
        fs::set_permissions(&wrapper, fs::Permissions::from_mode(0o755)).unwrap();
        let mut daemon_rustc = rustc.clone();
        daemon_rustc.cargo_command = wrapper.into();
        let first =
            build_native_shim_at(false, &daemon_rustc, &a, None, GuestInstrumentation::None)
                .unwrap();
        link(&first, 17);
        for _ in 0..100 {
            if ready.exists() {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(10));
        }
        assert!(
            ready.exists(),
            "wrapper's long-lived child never became ready"
        );
        std::thread::scope(|scope| {
            let (tx, rx) = std::sync::mpsc::sync_channel(1);
            let next = scope.spawn(move || {
                let built = build_native_shim_at(
                    false,
                    &daemon_rustc,
                    &b,
                    None,
                    GuestInstrumentation::None,
                );
                tx.send(()).unwrap();
                built
            });
            let unblocked = rx.recv_timeout(std::time::Duration::from_secs(30)).is_ok();
            drop(resume); // release the server even when detecting the regression
            let built = next.join().unwrap().unwrap();
            assert!(
                unblocked,
                "a wrapper daemon retained the exclusive build lock"
            );
            link(&built, 29);
        });

        let builds = native_shim_cache_base(cache.path(), None)
            .unwrap()
            .join("builds");
        let work = fs::read_dir(builds)
            .unwrap()
            .map(|e| e.unwrap().path())
            .find(|p| p.is_dir())
            .unwrap();
        let release =
            build_native_shim_at(true, &rustc, &a, None, GuestInstrumentation::None).unwrap();
        link(&release, 17);
        let debug =
            build_native_shim_at(false, &rustc, &a, None, GuestInstrumentation::None).unwrap();
        link(&debug, 17);
        assert!(
            work.join("target/debug")
                .join(NATIVE_SHIM_STATICLIB)
                .exists()
        );
        assert!(
            work.join("target/release")
                .join(NATIVE_SHIM_STATICLIB)
                .exists()
        );
        assert_ne!(release.staticlib, debug.staticlib);
        let growth = work.join("target/oversized-scratch");
        fs::File::create(&growth)
            .unwrap()
            .set_len(shim_cache::BUILD_BYTES + 1)
            .unwrap();
        // Model an old torn entry: the completion marker is missing but the
        // bundle marker survived alongside a broken private copy. Retrying A must
        // replace it, and oversized scratch must actually be removed.
        fs::remove_file(work.join("source").join(shim_cache::COMPLETE)).unwrap();
        // Keep the old bundle marker: it alone is not proof of source integrity.
        fs::write(
            work.join("source/patina-dst-native-shim/src/lib.rs"),
            "compile_error!(\"incomplete source switch\");",
        )
        .unwrap();
        let restored =
            build_native_shim_at(false, &rustc, &a, None, GuestInstrumentation::None).unwrap();
        link(&restored, 17);
        assert!(!growth.exists());
    }

    #[test]
    fn a_same_version_toolchain_split_still_names_the_difference() {
        // Two compilers can print the same banner and still be different builds
        // (a rebuilt nightly, a vendored rustc). The banner alone would then read
        // as a contradiction — "these two identical toolchains disagree" — so the
        // refusal falls back to the full `-vV` blocks.
        let shim = RustcIdentity {
            banner: "rustc 1.90.0 (aaaaaaaaa 2026-01-01)".into(),
            verbose: "rustc 1.90.0 (aaaaaaaaa 2026-01-01)\ncommit-hash: aaaaaaaaa\nLLVM version: \
                      20.1.0"
                .into(),
        };
        let guest = RustcIdentity {
            banner: shim.banner.clone(),
            verbose: "rustc 1.90.0 (aaaaaaaaa 2026-01-01)\ncommit-hash: bbbbbbbbb\nLLVM version: \
                      21.1.0"
                .into(),
        };
        assert_ne!(shim, guest);
        let message = toolchain_mismatch_message(
            &shim,
            Path::new("/patina"),
            &guest,
            Path::new("/work/guest"),
        );
        assert!(message.contains("refusing to build"), "{message}");
        assert!(
            message.contains("/patina") && message.contains("/work/guest"),
            "{message}"
        );
        assert!(
            message.contains("commit-hash: aaaaaaaaa")
                && message.contains("commit-hash: bbbbbbbbb"),
            "the same-banner case must show the full identities:\n{message}"
        );
        assert!(message.contains("No ambient fallback"), "{message}");
        assert!(
            message.contains("absolute, matching RUSTC and CARGO"),
            "{message}"
        );

        // Differing banners are self-explanatory; no full dump.
        let other = RustcIdentity {
            banner: "rustc 1.98.1 (48a229cea 2026-09-01)".into(),
            verbose: "rustc 1.98.1 (48a229cea 2026-09-01)\ncommit-hash: 48a229cea".into(),
        };
        let message =
            toolchain_mismatch_message(&shim, Path::new("/patina"), &other, Path::new("/g"));
        assert!(message.contains("rustc 1.98.1"), "{message}");
        assert!(
            !message.contains("commit-hash: 48a229cea"),
            "differing banners need no full dump:\n{message}"
        );
    }

    // A guest relinks when the shim changes because the staticlib it links is
    // named by its bytes and Cargo fingerprints the `cargo rustc --` link
    // arguments. Same bytes must publish to the same path (an unchanged rebuild
    // stays a cache hit and stores nothing new); changed bytes, even at the same
    // length, to a new one; and a published copy never changes afterwards.
    #[test]
    fn published_shim_staticlib_is_named_by_its_bytes() {
        let directory = tempfile::tempdir().unwrap();
        let staticlib = directory.path().join(NATIVE_SHIM_STATICLIB);
        let identity = RustcIdentity {
            banner: "test".into(),
            verbose: "test complete identity".into(),
        };
        let publish = || {
            publish_native_shim(&staticlib, directory.path(), "bundle", &identity, "debug").unwrap()
        };
        fs::write(&staticlib, b"shim bytes").unwrap();
        let first = publish();
        let abandoned = first._lease.dir.join("archive.partial");
        fs::write(&abandoned, b"interrupted publication").unwrap();
        assert_eq!(publish().staticlib, first.staticlib);
        assert!(!abandoned.exists());

        fs::write(&staticlib, b"shim bytez").unwrap();
        let flipped = publish();
        fs::write(&staticlib, b"rebuilt shim bytes").unwrap();
        let rebuilt = publish();
        assert_ne!(
            first.staticlib, flipped.staticlib,
            "a same-length edit must publish a new name"
        );
        assert_ne!(first.staticlib, rebuilt.staticlib);
        assert_ne!(flipped.staticlib, rebuilt.staticlib);

        assert_eq!(fs::read(&first.staticlib).unwrap(), b"shim bytes");
        assert_eq!(fs::read(&flipped.staticlib).unwrap(), b"shim bytez");
        assert_eq!(fs::read(&rebuilt.staticlib).unwrap(), b"rebuilt shim bytes");
    }
}
