//! Filesystem ABI adapters; all effects use the existing filesystem model.
use super::{at, cancel, error, model_result, size_result};
#[cfg(target_os = "linux")]
use crate::paths::RESOLVE_EMPTY_PATH;
use crate::paths::{AT_FDCWD, RESOLVE_NOFOLLOW};
use core::ffi::{c_char, c_int};
mod directory;
pub(super) mod metadata;
mod paths;
mod times;
#[cfg(target_os = "linux")]
mod volume;
#[cfg(target_os = "linux")]
mod xattr;

#[cfg(target_os = "linux")]
const AT_EMPTY_PATH: c_int = libc::AT_EMPTY_PATH;
#[cfg(target_os = "macos")]
const AT_EMPTY_PATH: c_int = 0;
#[cfg(target_os = "linux")]
const AT_FLAG_REFUSAL: c_int = libc::EINVAL;
#[cfg(target_os = "macos")]
const AT_FLAG_REFUSAL: c_int = libc::ENOSYS;

#[cfg(target_os = "linux")]
core::arch::global_asm!(
    ".globl patina_route___open64_2",
    ".hidden patina_route___open64_2",
    ".set patina_route___open64_2, __open64_2",
    ".globl patina_route___open_2",
    ".hidden patina_route___open_2",
    ".set patina_route___open_2, __open_2",
    ".globl patina_route___openat64_2",
    ".hidden patina_route___openat64_2",
    ".set patina_route___openat64_2, __openat64_2",
    ".globl patina_route___openat_2",
    ".hidden patina_route___openat_2",
    ".set patina_route___openat_2, __openat_2",
    ".globl patina_route___readlink_chk",
    ".hidden patina_route___readlink_chk",
    ".set patina_route___readlink_chk, __readlink_chk",
    ".globl patina_route___readlinkat_chk",
    ".hidden patina_route___readlinkat_chk",
    ".set patina_route___readlinkat_chk, __readlinkat_chk",
    ".globl patina_route_access",
    ".hidden patina_route_access",
    ".set patina_route_access, access",
    ".globl patina_route_chdir",
    ".hidden patina_route_chdir",
    ".set patina_route_chdir, chdir",
    ".globl patina_route_chmod",
    ".hidden patina_route_chmod",
    ".set patina_route_chmod, chmod",
    ".globl patina_route_chown",
    ".hidden patina_route_chown",
    ".set patina_route_chown, chown",
    ".globl patina_route_closedir",
    ".hidden patina_route_closedir",
    ".set patina_route_closedir, closedir",
    ".globl patina_route_creat",
    ".hidden patina_route_creat",
    ".set patina_route_creat, creat",
    ".globl patina_route_dirfd",
    ".hidden patina_route_dirfd",
    ".set patina_route_dirfd, dirfd",
    ".globl patina_route_faccessat",
    ".hidden patina_route_faccessat",
    ".set patina_route_faccessat, faccessat",
    ".globl patina_route_fallocate",
    ".hidden patina_route_fallocate",
    ".set patina_route_fallocate, fallocate",
    ".globl patina_route_fallocate64",
    ".hidden patina_route_fallocate64",
    ".set patina_route_fallocate64, fallocate64",
    ".globl patina_route_fchdir",
    ".hidden patina_route_fchdir",
    ".set patina_route_fchdir, fchdir",
    ".globl patina_route_fchmod",
    ".hidden patina_route_fchmod",
    ".set patina_route_fchmod, fchmod",
    ".globl patina_route_fchmodat",
    ".hidden patina_route_fchmodat",
    ".set patina_route_fchmodat, fchmodat",
    ".globl patina_route_fchown",
    ".hidden patina_route_fchown",
    ".set patina_route_fchown, fchown",
    ".globl patina_route_fchownat",
    ".hidden patina_route_fchownat",
    ".set patina_route_fchownat, fchownat",
    ".globl patina_route_fdopendir",
    ".hidden patina_route_fdopendir",
    ".set patina_route_fdopendir, fdopendir",
    ".globl patina_route_fgetxattr",
    ".hidden patina_route_fgetxattr",
    ".set patina_route_fgetxattr, fgetxattr",
    ".globl patina_route_flistxattr",
    ".hidden patina_route_flistxattr",
    ".set patina_route_flistxattr, flistxattr",
    ".globl patina_route_fremovexattr",
    ".hidden patina_route_fremovexattr",
    ".set patina_route_fremovexattr, fremovexattr",
    ".globl patina_route_fsetxattr",
    ".hidden patina_route_fsetxattr",
    ".set patina_route_fsetxattr, fsetxattr",
    ".globl patina_route_fstat",
    ".hidden patina_route_fstat",
    ".set patina_route_fstat, fstat",
    ".globl patina_route_fstat64",
    ".hidden patina_route_fstat64",
    ".set patina_route_fstat64, fstat64",
    ".globl patina_route_fstatat",
    ".hidden patina_route_fstatat",
    ".set patina_route_fstatat, fstatat",
    ".globl patina_route_fstatat64",
    ".hidden patina_route_fstatat64",
    ".set patina_route_fstatat64, fstatat64",
    ".globl patina_route_fstatfs",
    ".hidden patina_route_fstatfs",
    ".set patina_route_fstatfs, fstatfs",
    ".globl patina_route_fstatfs64",
    ".hidden patina_route_fstatfs64",
    ".set patina_route_fstatfs64, fstatfs64",
    ".globl patina_route_fstatvfs",
    ".hidden patina_route_fstatvfs",
    ".set patina_route_fstatvfs, fstatvfs",
    ".globl patina_route_fstatvfs64",
    ".hidden patina_route_fstatvfs64",
    ".set patina_route_fstatvfs64, fstatvfs64",
    ".globl patina_route_futimens",
    ".hidden patina_route_futimens",
    ".set patina_route_futimens, futimens",
    ".globl patina_route_futimes",
    ".hidden patina_route_futimes",
    ".set patina_route_futimes, futimes",
    ".globl patina_route_futimesat",
    ".hidden patina_route_futimesat",
    ".set patina_route_futimesat, futimesat",
    ".globl patina_route_getcwd",
    ".hidden patina_route_getcwd",
    ".set patina_route_getcwd, getcwd",
    ".globl patina_route_getdents64",
    ".hidden patina_route_getdents64",
    ".set patina_route_getdents64, getdents64",
    ".globl patina_route_getxattr",
    ".hidden patina_route_getxattr",
    ".set patina_route_getxattr, getxattr",
    ".globl patina_route_lchown",
    ".hidden patina_route_lchown",
    ".set patina_route_lchown, lchown",
    ".globl patina_route_lgetxattr",
    ".hidden patina_route_lgetxattr",
    ".set patina_route_lgetxattr, lgetxattr",
    ".globl patina_route_link",
    ".hidden patina_route_link",
    ".set patina_route_link, link",
    ".globl patina_route_linkat",
    ".hidden patina_route_linkat",
    ".set patina_route_linkat, linkat",
    ".globl patina_route_listxattr",
    ".hidden patina_route_listxattr",
    ".set patina_route_listxattr, listxattr",
    ".globl patina_route_llistxattr",
    ".hidden patina_route_llistxattr",
    ".set patina_route_llistxattr, llistxattr",
    ".globl patina_route_lremovexattr",
    ".hidden patina_route_lremovexattr",
    ".set patina_route_lremovexattr, lremovexattr",
    ".globl patina_route_lsetxattr",
    ".hidden patina_route_lsetxattr",
    ".set patina_route_lsetxattr, lsetxattr",
    ".globl patina_route_lstat",
    ".hidden patina_route_lstat",
    ".set patina_route_lstat, lstat",
    ".globl patina_route_lstat64",
    ".hidden patina_route_lstat64",
    ".set patina_route_lstat64, lstat64",
    ".globl patina_route_lutimes",
    ".hidden patina_route_lutimes",
    ".set patina_route_lutimes, lutimes",
    ".globl patina_route_mkdir",
    ".hidden patina_route_mkdir",
    ".set patina_route_mkdir, mkdir",
    ".globl patina_route_mkdirat",
    ".hidden patina_route_mkdirat",
    ".set patina_route_mkdirat, mkdirat",
    ".globl patina_route_mkfifo",
    ".hidden patina_route_mkfifo",
    ".set patina_route_mkfifo, mkfifo",
    ".globl patina_route_mkfifoat",
    ".hidden patina_route_mkfifoat",
    ".set patina_route_mkfifoat, mkfifoat",
    ".globl patina_route_mknod",
    ".hidden patina_route_mknod",
    ".set patina_route_mknod, mknod",
    ".globl patina_route_mknodat",
    ".hidden patina_route_mknodat",
    ".set patina_route_mknodat, mknodat",
    ".globl patina_route_opendir",
    ".hidden patina_route_opendir",
    ".set patina_route_opendir, opendir",
    ".globl patina_route_posix_fadvise",
    ".hidden patina_route_posix_fadvise",
    ".set patina_route_posix_fadvise, posix_fadvise",
    ".globl patina_route_posix_fadvise64",
    ".hidden patina_route_posix_fadvise64",
    ".set patina_route_posix_fadvise64, posix_fadvise64",
    ".globl patina_route_posix_fallocate",
    ".hidden patina_route_posix_fallocate",
    ".set patina_route_posix_fallocate, posix_fallocate",
    ".globl patina_route_posix_fallocate64",
    ".hidden patina_route_posix_fallocate64",
    ".set patina_route_posix_fallocate64, posix_fallocate64",
    ".globl patina_route_readdir",
    ".hidden patina_route_readdir",
    ".set patina_route_readdir, readdir",
    ".globl patina_route_readdir64",
    ".hidden patina_route_readdir64",
    ".set patina_route_readdir64, readdir64",
    ".globl patina_route_readdir64_r",
    ".hidden patina_route_readdir64_r",
    ".set patina_route_readdir64_r, readdir64_r",
    ".globl patina_route_readdir_r",
    ".hidden patina_route_readdir_r",
    ".set patina_route_readdir_r, readdir_r",
    ".globl patina_route_readlink",
    ".hidden patina_route_readlink",
    ".set patina_route_readlink, readlink",
    ".globl patina_route_readlinkat",
    ".hidden patina_route_readlinkat",
    ".set patina_route_readlinkat, readlinkat",
    ".globl patina_route_realpath",
    ".hidden patina_route_realpath",
    ".set patina_route_realpath, realpath",
    ".globl patina_route_removexattr",
    ".hidden patina_route_removexattr",
    ".set patina_route_removexattr, removexattr",
    ".globl patina_route_rename",
    ".hidden patina_route_rename",
    ".set patina_route_rename, rename",
    ".globl patina_route_renameat",
    ".hidden patina_route_renameat",
    ".set patina_route_renameat, renameat",
    ".globl patina_route_renameat2",
    ".hidden patina_route_renameat2",
    ".set patina_route_renameat2, renameat2",
    ".globl patina_route_rewinddir",
    ".hidden patina_route_rewinddir",
    ".set patina_route_rewinddir, rewinddir",
    ".globl patina_route_rmdir",
    ".hidden patina_route_rmdir",
    ".set patina_route_rmdir, rmdir",
    ".globl patina_route_seekdir",
    ".hidden patina_route_seekdir",
    ".set patina_route_seekdir, seekdir",
    ".globl patina_route_setxattr",
    ".hidden patina_route_setxattr",
    ".set patina_route_setxattr, setxattr",
    ".globl patina_route_stat",
    ".hidden patina_route_stat",
    ".set patina_route_stat, stat",
    ".globl patina_route_stat64",
    ".hidden patina_route_stat64",
    ".set patina_route_stat64, stat64",
    ".globl patina_route_statfs",
    ".hidden patina_route_statfs",
    ".set patina_route_statfs, statfs",
    ".globl patina_route_statfs64",
    ".hidden patina_route_statfs64",
    ".set patina_route_statfs64, statfs64",
    ".globl patina_route_statvfs",
    ".hidden patina_route_statvfs",
    ".set patina_route_statvfs, statvfs",
    ".globl patina_route_statvfs64",
    ".hidden patina_route_statvfs64",
    ".set patina_route_statvfs64, statvfs64",
    ".globl patina_route_statx",
    ".hidden patina_route_statx",
    ".set patina_route_statx, statx",
    ".globl patina_route_symlink",
    ".hidden patina_route_symlink",
    ".set patina_route_symlink, symlink",
    ".globl patina_route_symlinkat",
    ".hidden patina_route_symlinkat",
    ".set patina_route_symlinkat, symlinkat",
    ".globl patina_route_telldir",
    ".hidden patina_route_telldir",
    ".set patina_route_telldir, telldir",
    ".globl patina_route_truncate",
    ".hidden patina_route_truncate",
    ".set patina_route_truncate, truncate",
    ".globl patina_route_truncate64",
    ".hidden patina_route_truncate64",
    ".set patina_route_truncate64, truncate64",
    ".globl patina_route_umask",
    ".hidden patina_route_umask",
    ".set patina_route_umask, umask",
    ".globl patina_route_unlink",
    ".hidden patina_route_unlink",
    ".set patina_route_unlink, unlink",
    ".globl patina_route_unlinkat",
    ".hidden patina_route_unlinkat",
    ".set patina_route_unlinkat, unlinkat",
    ".globl patina_route_utime",
    ".hidden patina_route_utime",
    ".set patina_route_utime, utime",
    ".globl patina_route_utimensat",
    ".hidden patina_route_utimensat",
    ".set patina_route_utimensat, utimensat",
    ".globl patina_route_utimes",
    ".hidden patina_route_utimes",
    ".set patina_route_utimes, utimes",
);
