#!/usr/bin/env python3
"""Generate the offline Rust syscall inventory; never classify runtime support."""
import argparse
import difflib
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'crates/patina-syscalls/src/generated.rs'
HEADER = '// @generated by scripts/refresh-syscalls.py; do not edit.\n// Immutable source provenance and target inventories; runtime policy lives in linux.rs.\n'
# Deliberately narrow Rust string/tuple grammar. No arbitrary Rust is evaluated.
STRING = r'"(?:[^"\\\n]|\\["\\nrt])*"'
RECORD = re.compile(r'    \((' + ', '.join([STRING] * 6) + r')\),')


def require(condition, message):
    if not condition:
        raise ValueError(message)


def fetch(url):
    request = urllib.request.Request(url, headers={'User-Agent': 'patina-syscall-refresh'})
    with urllib.request.urlopen(request, timeout=60) as response:
        data = response.read()
    require(data, f'empty upstream response: {url}')
    return data


def provenance(text):
    start = 'pub const SOURCES: &[(&str, &str, &str, &str, &str, &str)] = &[\n'
    require(text.count(start) == 1, 'missing/duplicate provenance record')
    body = text.split(start)[1].split('\n];', 1)[0]
    records = []
    for line in body.splitlines():
        if re.fullmatch(r'    #\[cfg\((?:target_os = "(?:linux|macos)"|all\(target_os = "linux", target_arch = "(?:x86_64|aarch64)"\))\)\]', line):
            continue
        match = RECORD.fullmatch(line)
        require(match is not None, f'malformed provenance: {line}')
        record = json.loads('[' + match[1] + ']')
        group, version, revision, path, url, digest = record
        require(group in ('linux', 'darwin') and version, 'invalid source group/version')
        require(re.fullmatch('[0-9a-f]{40}', revision), 'invalid source revision')
        require(re.fullmatch('[0-9a-f]{64}', digest), 'invalid source hash')
        repo = 'torvalds/linux' if group == 'linux' else 'apple-oss-distributions/xnu'
        # Stable refreshes use the official stable mirror, rather than Torvalds' tree.
        allowed = [f'https://raw.githubusercontent.com/{repo}/{revision}/{path}']
        if group == 'linux':
            allowed.append(f'https://raw.githubusercontent.com/gregkh/linux/{revision}/{path}')
        require(url in allowed, 'provenance URL/revision/path mismatch')
        records.append(record)
    require(len({(r[0], r[3]) for r in records}) == len(records), 'duplicate source')
    for group in ('linux', 'darwin'):
        require(len({(r[1], r[2]) for r in records if r[0] == group}) == 1,
                f'incoherent {group} source pin')
    return records


def linux(text, arch, selector):
    require(re.findall(r'^syscall_abis_64 \+= (.*)$', selector, re.M) ==
            ['renameat rlimit memfd_secret'], 'ARM64 ABI selection changed')
    abis = {'common', '64'}
    if arch == 'aarch64':
        abis.update(('renameat', 'rlimit', 'memfd_secret'))
    rows = []
    known = {'common', '64', 'x32'} if arch == 'x86_64' else {
        'common', '64', '32', 'time32', 'stat64', 'renameat', 'rlimit',
        'memfd_secret', 'arc', 'csky', 'nios2', 'or1k', 'riscv', 'time64'}
    for line in text.splitlines():
        if not line.strip() or line.startswith('#'):
            continue
        fields = line.split()
        require(3 <= len(fields) <= 6 and fields[0].isdigit(), f'malformed Linux row: {line}')
        nr, abi, name = fields[:3]
        require(abi in known and re.fullmatch(r'[a-zA-Z_][a-zA-Z_0-9]*', name),
                f'unknown Linux ABI/name: {line}')
        if abi not in abis:
            continue
        entry = fields[3] if len(fields) > 3 and fields[3] != 'sys_ni_syscall' else None
        rows.append(dict(nr=int(nr), abi=abi, name=name, entry=entry))
    require(rows and len({r['nr'] for r in rows}) == len(rows), 'empty/duplicate Linux numbers')
    require(len({r['name'] for r in rows}) == len(rows), 'duplicate Linux names')
    return sorted(rows, key=lambda r: r['nr'])


def section(text, start, end):
    require(text.count(start) == 1, f'missing/duplicate source section: {start}')
    tail = text.split(start)[1]
    require(end in tail, f'unclosed source section: {start}')
    return tail.split(end)[0]


def darwin_table(text, namespace):
    if namespace == 'mach':
        text = section(text, 'const mach_trap_t       mach_trap_table[MACH_TRAP_TABLE_COUNT] = {', '\n};')
    rows = []
    condition = None
    otherwise = False
    for line in map(str.strip, text.splitlines()):
        if not line or (namespace == 'bsd' and (line.startswith(';') or line.startswith('#include <'))):
            continue
        if line.startswith('#if '):
            require(condition is None, 'nested source guard')
            condition = line[4:].split('/*')[0].strip()
            require(condition, 'empty source guard')
            otherwise = False
            continue
        if line == '#else' or line.startswith('#else '):
            require(condition is not None and not otherwise, 'unmatched source else')
            otherwise = True
            continue
        if line == '#endif' or line.startswith('#endif '):
            require(condition is not None, 'unmatched source endif')
            condition = None
            otherwise = False
            continue
        if namespace == 'bsd':
            match = re.fullmatch(r'(\d+)\s+AUE_\w+\s+(ALL|[TNHP]+)\s+\{([^}]+)\}(.*)', line)
            require(match is not None, f'malformed BSD row: {line}')
            slot = int(match[1])
            prototype, tail = match[3], match[4]
            require(not tail.strip() or (tail.strip() == '}' and slot in (501, 522)) or
                    (tail.strip().startswith('{') and tail.strip().endswith('}')), 'bad BSD annotation')
            function = re.fullmatch(r'.*?\b([A-Za-z_]\w*)\s*\([^)]*\)\s*(?:NO_SYSCALL_STUB\s*)?;\s*', prototype.strip())
            require(function is not None, f'bad BSD prototype: {line}')
            name = function[1]
        else:
            if line == '/* traps 100-107 reserved for IOKit */':
                continue
            match = re.fullmatch(r'/\* (\d+) \*/ MACH_TRAP\((.*)\),(?:\s*/\*.*\*/)?', line)
            require(match is not None, f'malformed Mach row: {line}')
            slot = int(match[1])
            args = list(map(str.strip, match[2].split(',')))
            require(len(args) in (4, 5) and args[1].isdigit() and args[2].isdigit() and
                    re.fullmatch(r'[A-Za-z_]\w*', args[3]) and
                    (len(args) == 4 or args[4] == '.mach_trap_returns_port = 1'), 'bad Mach arguments')
            name = args[0]
        require(re.fullmatch(r'[A-Za-z_]\w*', name), 'invalid Darwin entry')
        guard = f'!({condition})' if otherwise else condition
        variant = dict(entry=name, condition=guard,
                       table_status={'nosys': 'nosys', 'enosys': 'enosys', 'kern_invalid': 'invalid'}.get(name, 'declared'),
                       declaration=line)
        if slot < len(rows):
            prior = rows[slot]['variants']
            require(len(prior) == 1 and prior[0]['condition'] and guard == f"!({prior[0]['condition']})",
                    'duplicate/non-complementary Darwin slot')
            prior.append(variant)
        else:
            require(slot == len(rows), f'missing/out-of-order {namespace} slot {slot}')
            rows.append(dict(namespace=namespace, nr=-slot if namespace == 'mach' else slot,
                             subcode=None, variants=[variant]))
    require(condition is None and rows, 'unclosed guard/empty Darwin source')
    require(all(r['variants'][0]['condition'] is None or len(r['variants']) == 2 for r in rows),
            'lost Darwin conditional alternative')
    return rows


def arm_entries(sources):
    dispatch = section(sources['osfmk/arm64/sleh.c'], 'handle_svc(arm_saved_state_t *state)\n{', '\n}\n')
    require(re.findall(r'^\s*case (.*)', dispatch, re.M) ==
            ['MACH_ARM_TRAP_ABSTIME:', 'MACH_ARM_TRAP_CONTTIME:'], 'unclassified ARM dispatch case')
    require(all(s in dispatch for s in ('trap_no == (int)PLATFORM_SYSCALL_TRAP_NO',
            'platform_syscall(state);', 'if (trap_no < 0)')), 'ARM selector routing changed')
    rows = []
    handlers = {'MACH_ARM_TRAP_ABSTIME': 'handle_mach_absolute_time_trap',
                'MACH_ARM_TRAP_CONTTIME': 'handle_mach_continuous_time_trap'}
    for line in sources['osfmk/mach/arm/traps.h'].splitlines():
        if not line.startswith('#define MACH_ARM_TRAP_'):
            continue
        fields = line.split()
        require(len(fields) == 3 and fields[1] in handlers, 'unclassified ARM special trap')
        name = handlers[fields[1]]
        require(f'case {fields[1]}:\n\t\t\t{name}(state);' in dispatch, 'ARM trap handler changed')
        rows.append(dict(namespace='arm-special', nr=int(fields[2]), subcode=None,
                         variants=[dict(entry=name, condition=None, table_status='declared', declaration=line)]))
    require(len(rows) == 2, 'ARM special inventory changed')
    selectors = re.findall(r'^#define PLATFORM_SYSCALL_TRAP_NO (\S+)$', sources['osfmk/arm64/proc_reg.h'], re.M)
    require(len(selectors) == 1, 'missing/duplicate platform selector')
    nr = int(selectors[0], 16)
    if nr >= 2**31:
        nr -= 2**32
    body = section(sources['osfmk/arm64/machine_routines.c'], 'platform_syscall(arm_saved_state_t *state)\n{', '\n}\n')
    require('get_saved_state_reg(state, 3)' in body and 'thread_exception_return();' in body,
            'platform selector/return changed')
    switch = section(body, 'switch (code) {', '\n\t}')
    compact = re.sub(r'\s', '', re.sub(r'/\*.*?\*/', '', switch, flags=re.S))
    require(compact.split('case')[1:] == [
        r'2:platform_syscall_kprintf("setcthreadself.\n");thread_set_cthread_self(get_saved_state_reg(state,0));break;',
        r'3:platform_syscall_kprintf("getcthreadself.\n");set_user_saved_state_reg(state,0,thread_get_cthread_self());break;',
        '0:', r'1:default:platform_syscall_kprintf("unknown:%d\n",code);break;'],
        'platform subcode/handler/fallthrough changed')
    for subcode, name in enumerate(('icache_flush', 'dcache_flush', 'thread_set_cthread_self', 'thread_get_cthread_self')):
        rows.append(dict(namespace='arm-platform', nr=nr, subcode=subcode,
                         variants=[dict(entry=name, condition=None, table_status='removed' if subcode < 2 else 'declared',
                                        declaration=f'platform_syscall x3={subcode}')]))
    return rows


def inventories(sources):
    selector = sources['arch/arm64/kernel/Makefile.syscalls']
    x86 = linux(sources['arch/x86/entry/syscalls/syscall_64.tbl'], 'x86_64', selector)
    arm = linux(sources['scripts/syscall.tbl'], 'aarch64', selector)
    darwin = darwin_table(sources['bsd/kern/syscalls.master'], 'bsd')
    darwin += darwin_table(sources['osfmk/kern/syscall_sw.c'], 'mach') + arm_entries(sources)
    keys = [(r['namespace'], r['nr'], r['subcode']) for r in darwin]
    require(len(set(keys)) == len(keys), 'duplicate Darwin identity')
    return x86, arm, darwin


def ident(name):
    # Preserve upstream spelling, including leading underscores, without collisions.
    return 'N_' + name


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def option(value):
    return 'None' if value is None else f'Some({quote(value) if isinstance(value, str) else value})'


def generate(records, sources):
    x86, arm, darwin = inventories(sources)
    out = [HEADER, '#[rustfmt::skip]\n',
           'pub const SOURCES: &[(&str, &str, &str, &str, &str, &str)] = &[\n']
    for r in records:
        cfg = 'target_os = "linux"' if r[0] == 'linux' else 'target_os = "macos"'
        if r[3] == 'arch/x86/entry/syscalls/syscall_64.tbl':
            cfg = 'all(target_os = "linux", target_arch = "x86_64")'
        elif r[3] in ('scripts/syscall.tbl', 'arch/arm64/kernel/Makefile.syscalls'):
            cfg = 'all(target_os = "linux", target_arch = "aarch64")'
        out.append(f'    #[cfg({cfg})]\n    (' + ', '.join(map(quote, r)) + '),\n')
    out += ['];\n']
    for arch, rows in [('x86_64', x86), ('aarch64', arm)]:
        out += [f'#[cfg(all(target_os = "linux", target_arch = "{arch}"))]\npub mod linux_{arch} {{\n',
                '#[allow(non_camel_case_types)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n#[repr(u32)]\npub enum Syscall {',
                *[f'{ident(r["name"])} = {r["nr"]},' for r in rows], '}\n',
                'impl Syscall {\npub const ALL: &\'static [Self] = &[',
                *[f'Self::{ident(r["name"])},' for r in rows], '];\n',
                'pub const fn number(self) -> u32 { self as u32 }\n',
                'pub const fn name(self) -> &\'static str { match self {',
                *[f'Self::{ident(r["name"])} => {quote(r["name"])},' for r in rows], '} }\n',
                'pub const fn from_nr(nr: u32) -> Option<Self> { match nr {',
                *[f'{r["nr"]} => Some(Self::{ident(r["name"])}),' for r in rows], '_ => None,} }\n}\n',
                'pub const ENTRIES: &[crate::LinuxEntry] = &[\n']
        for r in rows:
            out.append('crate::LinuxEntry {' +
                       f'id: Syscall::{ident(r["name"])}, nr: {r["nr"]}, abi: {quote(r["abi"])}, name: {quote(r["name"])}, entry: {option(r["entry"]) }' + '},\n')
        out += ['];\n}\n']
    out += ['#[cfg(all(target_os = "macos", target_arch = "aarch64"))]\npub mod darwin_aarch64 {\nuse crate::{DarwinEntry, Variant};\n',
            '#[allow(non_camel_case_types)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum Syscall {\n']
    def darwin_id(r):
        return {'bsd': 'Bsd', 'mach': 'Mach', 'arm-special': 'ArmSpecial', 'arm-platform': 'ArmPlatform'}[r['namespace']] + str(abs(r['nr'])) + (f'Sub{r["subcode"]}' if r['subcode'] is not None else '') + '_' + r['variants'][0]['entry']
    out += [f'{darwin_id(r)},\n' for r in darwin]
    out += ['}\nimpl Syscall {\npub const fn number(self) -> i64 { self.entry().nr }\npub const fn entry(self) -> &\'static DarwinEntry { match self {',
            *[f'Self::{darwin_id(r)} => &ENTRIES[{i}],' for i, r in enumerate(darwin)], '} }\n}\n',
            'pub const ENTRIES: &[DarwinEntry] = &[\n']
    for r in darwin:
        out.append(f'DarwinEntry {{id: Syscall::{darwin_id(r)}, namespace: {quote(r["namespace"])}, nr: {r["nr"]}, subcode: {option(r["subcode"])}, variants: &[\n')
        for v in r['variants']:
            out.append(f'Variant {{entry: {quote(v["entry"])}, condition: {option(v["condition"])}, table_status: {quote(v["table_status"])}, declaration: {quote(v["declaration"])}}},\n')
        out.append(']},\n')
    out += ['];\n}\n']
    # rustfmt is a maintainer tool only; normal builds consume the result directly.
    result = subprocess.run(['rustfmt', '--edition', '2024', '--emit', 'stdout'],
                            input=''.join(out), text=True, capture_output=True, check=True)
    return result.stdout


def linux_release(version):
    """Order Linux major.minor[.patch][-rcN], with finals after their RCs."""
    match = re.fullmatch(r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:\.(0|[1-9][0-9]*))?(?:-rc([1-9][0-9]*))?', version)
    require(match is not None, f'invalid Linux release: {version!r}')
    major, minor, patch, rc = match.groups()
    return (int(major), int(minor), int(patch or 0), rc is None, int(rc or 0))


def latest(records):
    releases = json.loads(fetch('https://www.kernel.org/releases.json'))['releases']
    candidates = [r for r in releases if r['moniker'] == 'stable']
    require(candidates, 'kernel.org has no stable release')
    version = max(candidates, key=lambda r: linux_release(r['version']))['version']
    def resolve(repo, tag):
        data = json.loads(fetch(f'https://api.github.com/repos/{repo}/commits/{tag}'))
        require(re.fullmatch('[0-9a-f]{40}', data['sha']), 'invalid resolved commit')
        return data['sha']
    linux_rev = resolve('gregkh/linux', 'v' + version)
    tags = []
    page = 1
    while True:
        batch = json.loads(fetch(f'https://api.github.com/repos/apple-oss-distributions/xnu/tags?per_page=100&page={page}'))
        require(isinstance(batch, list), 'invalid XNU release list')
        tags.extend(t for t in batch if re.fullmatch(r'xnu-\d+(?:\.\d+)+', t['name']))
        if len(batch) < 100:
            break
        page += 1
    require(tags, 'no official XNU release tags')
    tag = max(tags, key=lambda t: tuple(map(int, t['name'][4:].split('.'))))
    xnu_rev = resolve('apple-oss-distributions/xnu', tag['name'])
    result = []
    for group, old_version, _, path, _, _ in records:
        new_version = version if group == 'linux' else tag['name']
        def xnu_release(v):
            require(re.fullmatch(r'xnu-\d+(?:\.\d+)+', v), f'invalid XNU release: {v!r}')
            return tuple(map(int, v[4:].split('.')))
        ordering = linux_release if group == 'linux' else xnu_release
        require(ordering(new_version) >= ordering(old_version),
                f'latest stable {new_version} predates pinned {old_version}; refusing inventory downgrade (no files changed)')
        revision = linux_rev if group == 'linux' else xnu_rev
        repo = 'gregkh/linux' if group == 'linux' else 'apple-oss-distributions/xnu'
        result.append([group, new_version, revision, path,
                       f'https://raw.githubusercontent.com/{repo}/{revision}/{path}', ''])
    return result


def download(records, update=False):
    sources = {}
    with tempfile.TemporaryDirectory(prefix='patina-syscall-sources-') as directory:
        for index, record in enumerate(records):
            path = Path(directory) / str(index)
            path.write_bytes(fetch(record[4]))
            data = path.read_bytes()
            digest = hashlib.sha256(data).hexdigest()
            require(update or digest == record[5], f'upstream hash mismatch: {record[4]}')
            record[5] = digest
            sources[record[3]] = data.decode('utf-8')
    return sources


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--latest', action='store_true', help='discover latest stable Linux and official XNU release (refuse downgrades)')
    action = parser.add_mutually_exclusive_group()
    action.add_argument('--apply', action='store_true', help='atomically replace generated.rs after complete validation')
    action.add_argument('--check', action='store_true', help='verify pinned regeneration (default)')
    args = parser.parse_args()
    old = OUTPUT.read_text()
    records = provenance(old)
    if args.latest:
        old_sources = download(records)
        previous = inventories(old_sources)
        records = latest(records)
        sources = download(records, update=True)
        current = inventories(sources)
        for before, after in zip(previous, current):
            def key(row):
                return (row.get('namespace', 'linux'), row['nr'], row.get('subcode'))
            after_keys = {key(r) for r in after}
            require(all(key(r) in after_keys for r in before), 'latest release removes inventory rows; explicit review required')
    else:
        sources = download(records)
    new = generate(records, sources)
    if new == old:
        print('syscall generation: PASS (pinned output reproducible)')
        return 0
    sys.stdout.writelines(difflib.unified_diff(old.splitlines(True), new.splitlines(True), fromfile=str(OUTPUT), tofile='regenerated'))
    if args.apply:
        # One complete Rust artifact: no mixed-target/provenance partial updates.
        with tempfile.NamedTemporaryFile(mode='w', dir=OUTPUT.parent, delete=False) as tmp:
            path = Path(tmp.name)
            tmp.write(new)
        try:
            os.replace(path, OUTPUT)
        finally:
            path.unlink(missing_ok=True)
        print('syscall generation: updated; review diff and classify new Linux IDs before building')
        return 0
    print('syscall generation: DRIFT (no files changed)', file=sys.stderr)
    return 1


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f'syscall generation: FAILED: {error}', file=sys.stderr)
        sys.exit(2)
